import * as THREE from 'three';
import { TerrainGenerator } from '../generation/terrain/terrainGenerator.ts';
import { InlandWaterManager } from '../generation/hydrology/inlandWaterManager.ts';
import { WaterShader } from '../generation/shaders/waterShader.ts';
import { PRNG } from '../generation/math/prng.ts';
function assert(ok:unknown,message:string){if(!ok)throw Error(message);}
const terrain=new TerrainGenerator(PRNG.hashString('Avalon'));
const feature=terrain.getHydrology().getWaterfalls()[0];
assert(feature,'waterfall generated');
const native=new THREE.ShaderMaterial({uniforms:THREE.UniformsUtils.clone(WaterShader.uniforms)});
const root=new THREE.Group(),manager=new InlandWaterManager(root,terrain.getHydrology(),native);
manager.updateObserver(feature.x,feature.z);
const camera=new THREE.PerspectiveCamera(75,1,.1,1000);
camera.position.set(feature.x+feature.fx*(feature.radius+15),2.4,feature.z+feature.fz*(feature.radius+15));
const target=new THREE.Vector3(feature.x,feature.upper*.5,feature.z);
camera.lookAt(target);camera.updateMatrixWorld();
let calls=0,currentTarget:THREE.WebGLRenderTarget|null=null;
const fake={shadowMap:{enabled:true},clippingPlanes:[],getRenderTarget:()=>currentTarget,
 setRenderTarget:(value:THREE.WebGLRenderTarget|null)=>{currentTarget=value;},clear:()=>{},render:()=>{calls++;}};
const renderer=fake as unknown as THREE.WebGLRenderer,scene=new THREE.Scene();
manager.renderSurfaceReflection(renderer,camera,scene);
assert(calls===1,'below spring level must render only the visible curtain');
assert(native.uniforms.uSpringReflectionReady.value===0,'hidden spring reflection disabled');
assert(native.uniforms.uCascadeReflectionReady.value===1,'curtain reflection available');
for(let i=0;i<30;i++)manager.renderSurfaceReflection(renderer,camera,scene);
assert(calls===1,'reuse cached reflection between scheduled updates');
assert(native.uniforms.uCascadeReflectionReady.value===1,'cached texture stays enabled');
assert(currentTarget===null&&fake.shadowMap.enabled,'renderer state restored');
camera.lookAt(camera.position.clone().addScaledVector(new THREE.Vector3(feature.fx,0,feature.fz),100));
camera.updateMatrixWorld();manager.renderSurfaceReflection(renderer,camera,scene);
assert(calls===1,'no extra world render when looking away');
assert(native.uniforms.uCascadeReflectionReady.value===0,'offscreen reflection disabled');
camera.position.set(feature.x-feature.fx*18+feature.fz*(feature.width*.5+2),feature.upper+4,feature.z-feature.fz*18-feature.fx*(feature.width*.5+2));
camera.lookAt(feature.x-feature.fx*18,feature.upper,feature.z-feature.fz*18);
camera.updateMatrixWorld();manager.renderSurfaceReflection(renderer,camera,scene);
assert(native.uniforms.uSpringReflectionReady.value===1,'spring reflection preserved when viewed from above');
const springCalls=calls;manager.renderSurfaceReflection(renderer,camera,scene);
assert(calls===springCalls,'spring reflection is cached too');
console.log(JSON.stringify({valid:true,extraRendersFor31Updates:1,hiddenSpringRenders:0,offscreenRenders:0}));
